### ISSUE TITLE
Parts links

### ISSUE THREAD

**Issue by marc-gist** [logichousepcb/Multi-Button-WS2812-RGB-esp8266-Decora#1]
Thank you for sharing! I'm looking at building some of these. Would you mind sharing links to the parts so that I ensure I get the correct size? notably the SMD ones.  Perhaps some photos as well.

Thank you!

**Comment by logichousepcb** [comment]
Have you already ordered some pcb’s?  I have a never version. I can send you a parts list if I know which version you plan to build.

**Comment by marc-gist** [comment]
I did order from the gerber's found here. I'm happy to order some of a new version too :)  I have most parts, but want to ensure I have/order correct size for the SMD.  I have some ESP32-C3-12F i may try on it as well.
Thanks!

**Comment by logichousepcb** [comment]
I’ll check it out later after work. I can’t remember which I posted there. I have 5 iterations of it. I do have some I c3 swapped.  I have a 6 button version with temp and motion as well.

**Comment by logichousepcb** [comment]
This is the button I used but there is also a thinner version that works
depending on the 3d printer button used.
https://www.amazon.com/gp/product/B07H9R9YMJ/ref=ppx_yo_dt_b_search_asin_title?ie=UTF8&psc=1

The AMS1117 is a standard 3.3 version

I used these leds but they are a standard size so a 5v ws2812 will work
since these are discontinued
https://www.lcsc.com/product-detail/Light-Emitting-Diodes-LED_Worldsemi-WS2812E_C139127.html

The resistors are 1206 size
10k and 4.7k

C4 =
https://www.lcsc.com/product-detail/Aluminum-Electrolytic-Capacitors-SMD_ROQANG-RVT1C100M0405_C72483.html
C3 =
https://www.lcsc.com/product-detail/Aluminum-Electrolytic-Capacitors-SMD_KNSCHA-RVT100UF10V67RV0036_C2891567.html

I hope that works.  Let me know if you have any questions

**Comment by marc-gist** [comment]
> I’ll check it out later after work. I can’t remember which I posted there. I have 5 iterations of it. I do have some I c3 swapped. I have a 6 button version with temp and motion as well. Sent from Mike's iPhone
> […](#)
> 

Do you have the tasmota pinout template for the C3 or esphome config?

**Comment by logichousepcb** [comment]
It’s bellow the esp-12f template in the github page.
